spring.application.name=auth
server.port=8081
logging.level.ru.videoplatform.auth=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/videoplatform_auth
spring.datasource.username=auth
spring.datasource.password=auth

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

app.security.jwt.secret=my-super-secret-key-32-symbols-minimum-length
app.security.jwt.access-token-lifetime=900s
app.security.jwt.refresh-token-lifetime=30d