spring.application.name=auth
server.port=8081
logging.level.ru.videoplatform.auth=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/videoplatform_auth
spring.datasource.username=auth
spring.datasource.password=auth

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false