spring.application.name=bot-service
server.port=${SERVER_PORT}

telegram.bot-token=${TELEGRAM_BOT_TOKEN}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}

services.booking-service.uri=${BOOKING_SERVICE_URI}