spring.application.name=notification-service
server.port=${SERVER_PORT}

spring.data.mongodb.uri=${MONGODB_URI}
services.bot-service.uri=${BOT_SERVICE_URI}

spring.data.mongodb.auto-index-creation=true
