spring.application.name=notification-service
server.port=${SERVER_PORT}

spring.datasource.url=${NOTIFICATION_DB_URL}
spring.datasource.username=${NOTIFICATION_DB_USERNAME}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}

services.bot-service.uri=${BOT_SERVICE_URI}