spring.application.name=booking-service
server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}

services.notification-service.uri=${NOTIFICATION_SERVICE_URI}